### ISSUE TITLE
Can NOT import androidlibrary in RIDE

### ISSUE THREAD

**Issue by uestcheng** [lovelysystems/robotframework-androidlibrary#56]
My issue pretty like #45, I add the calabash-android location to system's path. but the error is like below:

20130922 13:51:38.410 [WARN]: Importing test library "AndroidLibrary" failed

Traceback (most recent call last):
Creating an instance of the test library 'AndroidLibrary' with no arguments failed: Couldn't find binary calabash-android
Traceback (most recent call last):
  File "C:\python27\lib\site-packages\AndroidLibrary__init__.py", line 46, in **init**
    'calabash-android'])
  File "C:\python27\lib\site-packages\AndroidLibrary__init__.py", line 65, in _env_command
    raise AssertionError("Couldn't find binary %s" % os.path.commonprefix(commands))
  File "C:\python27\lib\site-packages\robotide\spec\librarymanager.py", line 76, in _fetch_keywords
    return get_import_result(path, library_args)
  File "C:\python27\lib\site-packages\robotide\spec\libraryfetcher.py", line 20, in get_import_result
    lib = TestLibrary(path, args)
  File "C:\python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 41, in TestLibrary
    lib.create_handlers()
  File "C:\python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 125, in create_handlers
    self._libinst = self.get_instance()
  File "C:\python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 191, in get_instance
    self._libinst = self._get_instance()
  File "C:\python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 199, in _get_instance
    self._raise_creating_instance_failed()
  File "C:\python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 254, in _raise_creating_instance_failed
    "failed: %s\n%s" % (self.name, args, msg, details))

Can anyone help me?

**Comment by Ethies** [comment]
Oopss... still not resolved ... now I am getting the same issue.

**Comment by Sumeet90** [comment]
I got the same issue please let me know if anyone is resolved...
