### ISSUE TITLE
Incompatibility with recent Robot Framework

### ISSUE THREAD

**Issue by alexeylubyanoy** [lovelysystems/robotframework-androidlibrary#68]
I get this exception when using Selenium2Library with the latest Robot Framework code:
Importing test library 'AndroidLibrary' failed: ImportError: cannot import name GLOBAL_VARIABLES
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/AndroidLibrary/__init__.py", line 13, in <module>
    from robot.variables import GLOBAL_VARIABLES
PYTHONPATH:
  /usr/local/bin
  /Library/Python/2.7/site-packages/pip-7.1.0-py2.7.egg
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
  /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
  /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
  /Library/Python/2.7/site-packages

Seems like it's smth similar to https://github.com/rtomac/robotframework-selenium2library/issues/429

**Comment by a-padinha** [comment]
Hello I'm getting the same error, did you find any solution ? 

Traceback (most recent call last):
  File "c:\python27\lib\site-packages\AndroidLibrary\__init__.py", line 13, in <module>
    from robot.variables import GLOBAL_VARIABLES
PYTHONPATH:
  c:\python27\python27.zip
  c:\python27\DLLs
  c:\python27\lib
  c:\python27\lib\plat-win
  c:\python27\lib\lib-tk
  c:\python27
  c:\python27\lib\site-packages
  c:\python27\lib\site-packages\wx-2.8-msw-unicode

**Comment by MichaelHallik** [comment]
As mentioned by Pekka Klärck (https://www.linkedin.com/grp/post/3710899-6032671543765590020?trk=groups-post-b-all-cmnts):

"AndroidLibrary uses Robot's internal API that has changed in RF 2.9. It needs to be fixed in AndroidLibrary but I don't know how actively it is maintained. Alternatively you can downgrade RF to 2.8.7."

Since the project looks kind of abandoned, I don't think you will get a fix soon.

Maybe give this a try instead: https://github.com/jollychang/robotframework-appiumlibrary?

**Comment by PravallikaKG** [comment]
Hi a-padinha,

I am also facing the same error 
'Importing test library 'AndroidLibrary' failed: ImportError: cannot import name GLOBAL_VARIABLES'

when i am trying to use Library AndroidLibrary in my robot script.
Is your issue resolved???? If resloved, Help me how to resolve it.

I installed it using following command:
pip install --upgrade robotframework-androidlibrary

and following are the revisions i am using:
robotframework (3.0)
robotframework-androidlibrary (0.2.0)
